name: discord-bot
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - discord.py
  - python-dotenv
  - pytorch
  - torchvision
  - pillow
  - boto3
  - requests